### ISSUE TITLE
Unable to detect Cypress when using Yarn Berry

### ISSUE THREAD

**Issue by mogusbi** [sorry-cypress/cy2#10]
When trying to run `cy2` after installing using Yarn v2 (Berry) and running it from a workspace, I get the following error `Error: Cannot detect cypress`.

I did some digging and I've noticed `npm-which` is returning a completely bogus path inside of the `/private/var/` folder.

If you swap `const which = require('npm-which')(process.cwd());` to `const which = require('npm-which')(__dirname);` on line 4 in `patch.js` it seems to fix the issue for me. I wanted to make the changes and raise a PR but I can't get any of the tests to run so I left it

Another alternative would be maybe using something like https://www.npmjs.com/package/find-yarn-workspace-root to try and detect if it's using Yarn workspaces and use the value returned from that rather than `process.cwd()`

**Comment by agoldis** [comment]
@mogusbi thanks for opening the issue. I have fixed the tests. Unfortunately, e2e tests are failing on window when using `__dirname`. Would be handy to have a reproducible example.

**Comment by mogusbi** [comment]
@agoldis I've created a repo to quickly reproduce the issue: https://github.com/mogusbi/cy2-yarn-berry-issue

Let me know if you need any more info

**Comment by rdadoune** [comment]
I'm also using Yarn Berry and this fix doesn't work for me. Luckily I was able to [patch](https://yarnpkg.com/cli/patch) with a fix that works: 
```javascript
// lib/patch.js
function getCypressCLIBinPath() {
  return new Promise((resolve) => {
    const binaryCypress = require.resolve('cypress/bin/cypress', {
      paths: [process.cwd()],
    });
    debug('Cypress binary: %s', binaryCypress);
    const packagePath = path.normalize(fs.realpathSync(binaryCypress));
    debug('Cypress normalized package path: %s', packagePath);
    return resolve(packagePath);
  });
}
```

**Comment by agoldis** [comment]
@rdadoune any chance you can try `npm i cy2@2.0.0-beta.0.`
