### ISSUE TITLE
Usage of globally installed cy2 and cypress

### ISSUE THREAD

**Issue by parky128** [sorry-cypress/cy2#12]
Hi,

We have sorry-cypress setup and in use with our ci (jenkins) builds.

The tests are getting executed on some AWS EC2 instances, the image thats being used on these has all the necessary [dependencies](https://docs.cypress.io/guides/continuous-integration/introduction#Dependencies) cypress requires.

Up to now we have been installing cypress locally on each EC2 instance when they get spun up and used for the test runs along with other additional dependencies we also need specific to our tests (plugins, reporters, etc).

e.g.

`npm i cypress cy2 cypress-mochawesome-reporter cypress-wait-until @bahmutov/cypress-extends typescript`

Then when it comes to issuing the test command we use the cy2 approach like so:

`sh "CYPRESS_API_URL=\"${CYPRESS_API_URL}:8080\" npx cy2 run --record --key XXX --parallel --ci-build-id ${env.BUILD_ID} --browser chrome --headless --config-file cypress/cypress.ci.json --env $envCredentials || true"`

This is all working fine, but we have the overhead of having to install cypress, cy2, locally (if not already installed from a previous run) and so we have been looking into globally installing cypress on the image we are using to save on some setup time.

Having now install cypress globally, we have modified our test command like so

`CYPRESS_API_URL=\"${CYPRESS_API_URL}:8080\" /home/jenkins/.npm-global/lib/node_modules/cypress/bin/cypress run --record --parallel --ci-build-id ${env.BUILD_ID} --browser chrome --headless --config-file cypress/cypress.ci.json --env $envCredentials || true`

But it bails with an error 
````
Your Record Key XXX...XXX is not valid with this project: bla

It may have been recently revoked by you or another user.

Please log into the Dashboard to see the valid record keys.
````

I think I see why as in our modified command, we are no longer using `cy2` and so the CYPRESS_API_URL arg is being ignored - we are just referencing the global cypress path for the run command

So my question is, if we were to install cy2 globally on our image used by our ec2 instances for our tests, do we need to make it aware of the globally installed version of cypress as well?

**Comment by agoldis** [comment]
`cy2` should just work with the global instance of cypress. Keep running it as usual:

```sh
sh "CYPRESS_API_URL=\"${CYPRESS_API_URL}:8080\" npx cy2 run --record --key XXX --parallel --ci-build-id ${env.BUILD_ID} --browser chrome --headless --config-file cypress/cypress.ci.json --env $envCredentials || true"
```
