### ISSUE TITLE
how can i run cy2 in nodejs and send all the data to my sorry-cypress service

### ISSUE THREAD

**Issue by cc8476** [sorry-cypress/cy2#18]
hi , i can run "cy2 run" by cli command  
such as "CYPRESS_API_URL='http://xx.xx.xx.xx:1234/'   ./node_modules/.bin/cy2 run --record --key xxxx-xxx-xxxx-xxxx-xxxx --parallel --ci-build-id `date +%s`  " 

but ,how to run in nodejs and get the result in nodejs
there is  my code below, but it doesn't work.
so someone tell me ,how to resolve the problem .  thanks !!!
`
const cypress = require('cypress');
const { patch,run } = require('cy2');

await patch('http://xx.xx.xx.xx:1234/');

cypress.run({
    config,
    spec: './cypress/integration/check_specific_room.js',
  }).then((results) => {
  console.log("i can get the result , but the  data  didn't be sent to the right server")
}
`

**Comment by agoldis** [comment]
1. Please follow the template
2. Please search issues and discussions for existing solutions

**Comment by cc8476** [comment]
i got it
i should add atrrs to config object 

example:
cypress.run({
    config,
    "key":"dc329702-a8b9-486f-ae9d-5cf2c8a5ffcc",
    "record":true,
    "parallel":true,
    "ciBuildId":new Date().toLocaleTimeString(),
    spec: './cypress/integration/check_specific_room.js',
  })
