### ISSUE TITLE
cy2 patches global cypress on first run

### ISSUE THREAD

**Issue by cakeinpanic** [sorry-cypress/cy2#19]
Hi, toady I spent 3 hours debugging why after I first ran `npx current --record` I could not use **cypress-dashboard** in _any_ of my projects on my machine getting error message
```
We encountered an unexpected error talking to our servers.
There is likely something wrong with the request.
The --tag flag you passed was: 
The server's response was:
StatusCodeError: 422
{
  "message": "Record key is invalid. Please visit https://app.currents.dev to see the valid record keys.",
  "errors": []
}
```

In the end I discovered that somehow cy2 patches cypress file `~/Library/Caches/Cypress/9.2.0/Cypress.app/Contents/Resources/app/packages/server/config/app.yml`

and setting up this
```
 production:
-  api_url: "https://api.cypress.io/"
-  on_url: "https://on.cypress.io/"
+  api_url: https://cy.currents.dev
+  on_url: https://on.cypress.io/
```

and the only way how I can fix it – reinstall Cypress completely on my machine
Not cool at all :(

**Comment by agoldis** [comment]
Sorry for the trouble, Katya.

Next time please run `CYPRESS_API_URL=https://api.cypress.io cy2...`

**Comment by cakeinpanic** [comment]
Thank you for the fast answer. You mean to run currents tests with `CYPRESS_API_URL=https://api.cypress.io` or cypress-dashboard tests?

**Comment by agoldis** [comment]
I mean to run `cy2`, while environment variable `CYPRESS_API_URL` is set to  `https://api.cypress.io`, like this:
```
CYPRESS_API_URL=https://api.cypress.io cy2 run <your usual flags>
```

Invoking `cy2` should patch your cypress installation with the default API url.

---

You can also copy the `~/Library/Caches/Cypress/9.2.0/Cypress.app/Contents/Resources/app/packages/server/config/_app.yml` to `~/Library/Caches/Cypress/9.2.0/Cypress.app/Contents/Resources/app/packages/server/config/app.yml` to restore the original cypress configuration.

**Comment by agoldis** [comment]
to be fair, we explicitly mention in the [documentation](https://docs.sorry-cypress.dev/cypress-agent/cy2) what's the effect of running `cy2`

> Running the command above will invoke your default cypress version with the flags you've provided. It will also modify the internal cypress configuration to use a different API URL.

**Comment by cakeinpanic** [comment]
Did not find this documentation when investigating the issue, had to dig into the `currents` package first to understand it was a `cy2` issue. Maybe it worth mentioning in relation with `currents` too

IMHO In the docs there should be more emphasis on the fact that to use anything other than cypress dashboard global cypress needs to be patched.
