### ISSUE TITLE
CYPRESS_API_URL should not have a default

### ISSUE THREAD

**Issue by rrauenza** [sorry-cypress/cy2#23]
> When CYPRESS_API_URL is not set, it just uses the default API server https://api.cypress.io

I think this is a security issue -- when self hosting, if I fail / forget to set this variable, I really don't want it attempting to send results out to some 3rd party....

**Comment by agoldis** [comment]
@rrauenza Please check-out https://www.npmjs.com/package/cy2/v/3.0.0-alpha.1

**Comment by agoldis** [comment]
Resolved in #26
