### ISSUE TITLE
Set user-agent header for initial request to sorry-cypress director

### ISSUE THREAD

**Issue by larntz** [sorry-cypress/cy2#25]
Hello, I am experiencing an issue where the initial request to the sorry-cypress director is blocked by our firewall because there is no `user-agent` header set.

I'm not sure if this is the right project for this issue. If it's not I apologize and pointing me to the right place would be greatly appreciated. 

Here's what is happening...

```
npx cy2 run -b chrome --config-file integration/config/cypress.config.ts --record --key unusedKey --parallel --ci-build-id asdf-1234 --config userAgent="asdf"
[cy2] Running cypress with API URL: https://sorry-cypress-backend.example.com

cypress-grep: filtering using tag(s) "-#bug+-#flaky"
We encountered an unexpected error talking to our servers.

Because you passed the --parallel flag, this run cannot proceed because it requires a valid response from our servers.

The --ciBuildId flag you passed was: asdf-1234

The server's response was:

StatusCodeError: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body>\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n</html>\r\n"
```

The 403 is coming from an aws waf rule that blocks requests without a `user-agent` header. 

I have tried adding the `userAgent` config option to the cypress.config.ts file and also on the command line as it is in the command above i.e., `--config userAgent="asdf"`, I've had one of our javascript developers look at this and he couldn't figure out a way to get the header set on this initial request (and possibly subsequent requests to the sorry-cypress director service). 

Is there a way to set the user-agent on these requests?

**Comment by agoldis** [comment]
Replied in Slack
