### ISSUE TITLE
cy2 is failing to set CYPRESS_API_URL

### ISSUE THREAD

**Issue by DriftedPrism** [sorry-cypress/cy2#29]
When I run: `CYPRESS_API_URL="http://localhost:1234/" npx cy2 run --parallel --record --key somekey --ci-build-id hello-cypress`

I am getting:
`[cy2] Running cypress with API URL: http://localhost:1234/
Error: EPERM: operation not permitted, open '/Users/foobar/Library/Caches/Cypress/10.11.0/Cypress.app/Contents/Resources/app/index.js'
    at Object.openSync (fs.js:498:3)
    at Object.writeFileSync (fs.js:1524:35)
    at Object.<anonymous> (/Users/foobar/node_modules/cy2/dist/patch.js:55:21)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/foobar/node_modules/cy2/dist/patch.js:17:28)
    at _next (/Users/foobar/node_modules/cy2/dist/patch.js:35:17) {
  errno: -1,
  syscall: 'open',
  code: 'EPERM',
  path: '/Users/foobar/Library/Caches/Cypress/10.11.0/Cypress.app/Contents/Resources/app/index.js'
}`

I am on a Mac (Ventura) and Crypress 10.11.0

Thanks!

**Comment by agoldis** [comment]
`/Users/foobar/Library/Caches/Cypress/10.11.0/Cypress.app/Contents/Resources/app/index.js` is not writable for the uid executing the `cy2` command. Not much we can do here, please fix the permissions.

**Comment by DriftedPrism** [comment]
> `/Users/foobar/Library/Caches/Cypress/10.11.0/Cypress.app/Contents/Resources/app/index.js` is not writable for the uid executing the `cy2` command. Not much we can do here, please fix the permissions.

Fix them to what exactly? I already have read/write on that file

**Comment by agoldis** [comment]
Please refer to https://trugman-internals.com/understanding-linux-uids/
