### ISSUE TITLE
Unable to modify contents of Cypress configuration file

### ISSUE THREAD

**Issue by dragancla** [sorry-cypress/cy2#30]
Hi,

Ever since upgrading my MacOS version to v13 a few days ago the cy2 module has stopped working for me:

```sh
CYPRESS_API_URL="https://sorry-cypress-demo-director.herokuapp.com/" npx cy2 run --parallel --record --key somekey --ci-build-id hello-cypress
[cy2] Running cypress with API URL: https://sorry-cypress-demo-director.herokuapp.com/
Error: EPERM: operation not permitted, open '/Users/dragancla/Library/Caches/Cypress/10.11.0/Cypress.app/Contents/Resources/app/index.js'
    at Object.openSync (node:fs:585:3)
    at Object.writeFileSync (node:fs:2170:35)
    at Object.<anonymous> (/Users/dragancla/app_path/node_modules/cy2/dist/patch.js:55:21)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/dragancla/app_path/node_modules/cy2/dist/patch.js:17:28)
    at _next (/Users/dragancla/app_path/node_modules/cy2/dist/patch.js:35:17) {
  errno: -1,
  syscall: 'open',
  code: 'EPERM',
  path: '/Users/dragancla/Library/Caches/Cypress/10.11.0/Cypress.app/Contents/Resources/app/index.js'
}
```

By the looks of things, it's something related to how the new MacOS Ventura is now handling write permissions in the ~/Library/Caches/ directory, as the code line that fails is basically `_fs.default.writeFileSync(serverInitPath, result);` which throws an EPERM error. Reinstalling the module or Cypress does not work. 

cy2 version: 3.0.0 - 3.1.7 (tried all of them but none work)
Cypress version: 10.11.0
MacOS: Ventura

**Comment by dragancla** [comment]
Worth mentioning that it might not affect users at all except if they run it locally. CI runs would most likely not have a MacOS environment (probably some version of alpine Linux) and that you have to set permissions manually if you plan to run this on a MacMini or AWS MacOS containers, which is a bit of a hassle.

**Comment by agoldis** [comment]
I have upgraded to Ventura as well and am not able to reproduce the issue. 
Is your shell allowed to access the FS? https://developer.apple.com/forums/thread/107546

**Comment by agoldis** [comment]
I've got this small popup: 

<img width="355" alt="CleanShot 2022-11-03 at 00 02 46@2x" src="https://user-images.githubusercontent.com/1637928/199663534-d43ea4b7-105e-45f2-b946-d4233d99b103.png">

Changing the Mac OS security settings would resolve the issue:

![CleanShot 2022-11-03 at 00 04 10@2x](https://user-images.githubusercontent.com/1637928/199663823-d6138143-f0fa-4f1a-ada8-8e1d49417930.png)

**Comment by dragancla** [comment]
> ![CleanShot 2022-11-03 at 00 04 10@2x](https://user-images.githubusercontent.com/1637928/199663823-d6138143-f0fa-4f1a-ada8-8e1d49417930.png)

As a matter of fact, that did it, but instead of iTerm I had to give permissions to Visual Studio Code. I was really struggling to understand why chflags and chmod didn't help me fix this locally yesterday. Thanks for the tip!
