### ISSUE TITLE
Failed to run Cypress 12.0.2

### ISSUE THREAD

**Issue by jiadesen** [sorry-cypress/cy2#35]
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/22772994/206750359-de43cf27-fe57-4fa4-95b0-a3fbb9fc43ab.png">

**Comment by jiadesen** [comment]
Cypress 12.0.1 can run

**Comment by jiadesen** [comment]
And there is no problem running directly with the `cypress run` command

**Comment by agoldis** [comment]
Seems like they are still figuring out the new packaging structure. I have a fix, will release later tonight

**Comment by agoldis** [comment]
@mikeShi42 do you have a good workaround to prevent future shenanigans? Please help with your Bart resources

**Comment by agoldis** [comment]
@jiadesen @xbj110825  fixed in [3.4.1](https://github.com/sorry-cypress/cy2/releases/tag/v3.4.1)

**Comment by MikeShi42** [comment]
@agoldis I'll shoot you an email - we don't have any good answers on our end either yet unfortunately 🙁

**Comment by agoldis** [comment]
@@xbj110825 any chance you can close the original issue in cypress repo?

**Comment by xbj110825** [comment]
@agoldis ok, I just close it.

**Comment by nguyenminhhuy89** [comment]
> Cypress 12.0.1 can run

it worked for me. thanks you
