### ISSUE TITLE
cypress verify failed when using ci cache

### ISSUE THREAD

**Issue by jiadesen** [sorry-cypress/cy2#37]
![image](https://user-images.githubusercontent.com/22772994/206951289-c49c5708-53bd-4e49-a88c-131cfc8b37f7.png)

**Comment by agoldis** [comment]
Please share cy2 and cypress version

**Comment by jiadesen** [comment]
cy2: 3.4.1
cypress: 12.0.2

**Comment by agoldis** [comment]
Is there any other outout above the cropped screenshot?
Also, please try running with `DEBUG=cy2*,cypress:*`

**Comment by jiadesen** [comment]
running with `DEBUG=cy2*,cypress:*`

> "npx cy2 run DEBUG=cy2*,cypress:* --parallel --record ..."

same result

![image](https://user-images.githubusercontent.com/22772994/206952536-f0301b85-ddd8-40aa-8efb-38896976d5bc.png)

**Comment by jiadesen** [comment]
It seems to be a problem with the ci caching strategy. I'll try to adjust it again...

**Comment by agoldis** [comment]
DEBUG=cy2*,cypress:* should go before the actual command - to set the env variables

**Comment by jiadesen** [comment]
It has been confirmed that the cypress application cache does not exist. Thank you very much!

![image](https://user-images.githubusercontent.com/22772994/206954264-fc272c13-842d-459f-9c7b-f7b4881051cc.png)

**Comment by matrunchyk** [comment]
Still having the same issue
cy2: 3.4.2
Cypress: 12.0.2

![image](https://user-images.githubusercontent.com/2089828/206997178-95abacda-4374-4df2-bb97-1051bf836136.png)

**Comment by matrunchyk** [comment]
Debug log
![image](https://user-images.githubusercontent.com/2089828/207000558-5d473f86-71a6-44a5-bb2e-af52171494ef.png)

I'm running Cypress in parallel with 3 agents, and interestingly only one of the agents has no issue.
Before upgrading to v12 it was working great.
