### ISSUE TITLE
Launch cypress using Module API cypress.run() with cy2

### ISSUE THREAD

**Issue by testingJava2** [sorry-cypress/cy2#4]
Hello,

Couldn't find any documentation or solution as to if we are able to use cy2 with cypress' Module API [e.g. cypress.run()]

[As documented here](https://docs.cypress.io/guides/guides/module-api#cypress-run).

Is this currently possible?

Thank you!

**Comment by testingJava2** [comment]
@agoldis, thank you, that worked great!

Although, in the end my pipe was throwing an error that cy2.patch cannot use await as it's not an async function 🤔
So I had to just use cy2.patch('http://cy.xoxo.com');

I saw that you pushed v1.0.5 to main - was it my misinterpretation or were these changed also introduced there as well?

Thank you again 🙂

**Comment by agoldis** [comment]
Weird, it is an `async` function https://github.com/sorry-cypress/cy2/pull/6/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R3

**Comment by testingJava2** [comment]
I agree, weird indeed. Not sure if it's something coming from my config, but I assume this shouldn't be the case.
Let me know if I can share something else in case you want to debug this 🙂

Thanks!

**Comment by rsouthgate** [comment]
@agoldis We're using a @nrwl builder to run our tests (https://www.npmjs.com/package/@nrwl/cypress). This essentially `requires` cypress. I'm wondering if it would be possible to alias cypress with cy2 in the webpack module loader... that would miss the line above where you explicitly call `cy2.patch`. is there any way to get the patch to happen automatically from a require?

**Comment by agoldis** [comment]
@rsouthgate I can add a dedicated file with side effects on `require` for that purpose, something like `require('cy2/apply-patch-on-require')`;

Note though:
- patching is async - i.e. unless you wait on a Promise returned from `cy2/apply-patch-on-require` you might theoretically start running cypress before patching.
- not sure how long that will last, given community's push for ES modules 

As an alternative, you could add the patch as [`entry`](https://webpack.js.org/configuration/entry-context/#entry) to webpack config. You could write your own module that invokes the patch - i.e. no need to change `cy2`

Re-exporting all of `cypress/cli` is also an option, but seems complicated based on what I currently know. 


What do you think?

**Comment by testingJava2** [comment]
@agoldis, after updating the cy2 package to v 1.1.1, and trying to run Cypress via the Module API, I have an error that some modules are missing.

Maybe I'm doing something wrong(?), but I've done the set-up as defined in the read-me:

```
const {patch} = require('cy2');
const cypress = require('cypress');

const CYPRESS_API_URL = 'https://myURIhere.com';

async function main() {
  await patch(CYPRESS_API_URL);
}

main().catch(console.error);

cypress
  .run(cypressConfigurationHere)
```

Do you see any issues with what I am doing?

The error I get is:

```
Error: Cannot find module '.\node_modules\.bin\node_modules\cypress\lib\tasks\state'
Require stack:
- .\node_modules\cy2\lib\patch.js
- .\node_modules\cy2\index.js
```
I am using Cypress 6.9.1, tried removing /node_modules and reinstall everything, but it did not fix this.

**Comment by agoldis** [comment]
I will give it a try on windows. You can `https://www.npmjs.com/package/cy2/v/1.1.0-beta.0` meanwhile

**Comment by testingJava2** [comment]
Thank you @agoldis 🙂
I will switch back to 1.1.0-beta.0, but looking forward for ^1.1.0, for the Windows support.
