### ISSUE TITLE
Run multiple instances of cypress on same machine

### ISSUE THREAD

**Issue by tomasz-hofy** [sorry-cypress/cy2#43]
I am running 4 parallel processes on the same machine. We have a setup which allows to run multiple tests in paralel with same backend. 
I am using the following approach
```
"scripts": {
    "ci-command": "xvfb-run -a npx cypress run --parallel --record --key XXX --ci-build-id sorry-cypress",
    "ci-run": "concurrently \"npm run ci-command\" \"npm run ci-command\" \"npm run ci-command\" \"npm run ci-command\""
  }
```
The issue I have is that I cannot "pre-patch" cypress with cy2, I am manually replacing `app.yml` for now in advance.

Could you provide some working example in Readme explaining how to run multiple instances of cypress(with cy2) on 1 machine ?

**Comment by agoldis** [comment]
Just run the same command on different terminals, e.g.:

```sh
CYPRESS_API_URL=<your_URL> npx cy2 run --parallel --record --key <key> --ci-build-id same-machine-001
```

https://user-images.githubusercontent.com/1637928/211273387-725afc09-fc6e-48ea-a6de-7c13ad8be5a4.mp4

I am using cy2@4.0.1. If you use older version of `cy2`, just patch cypress version once. Please note, running cypress on the same CI linux machine is not recommended.

**Comment by tomasz-hofy** [comment]
the problem appears when you run them at the same time, as each cy2 tries to patch at the same time.

**Comment by tomasz-hofy** [comment]
> Please note, running cypress on the same CI linux machine is not recommended.
Why its not recommended ? I have 32 cores, want to use them :D

**Comment by matrunchyk** [comment]
> Please note, running cypress on the same CI linux machine is not recommended.
Same question, this is our typical use case and switching to another setup is not an option for us at the moment.

**Comment by agoldis** [comment]
@tomasz-hofy @matrunchyk they mention that in their documentation and issues. AFAIK the problem is not resources allocation, but the fact that two runs can interfere one with another (because of Xvfb, screenshots and videos deletion). 

There's no problem with using cy2 though.

**Comment by matrunchyk** [comment]
That all sounds reasonable to me (and actually we have had troubles in test-coverage report generation, which we solved by implementing a file lock mechanism, which is an entirely different topic).

But the funny thing is it all works with `cypress@10.8.0` and `cy2@2.0.1`. And stopped working when we upgraded to Cypress 12. (I have `cypress@12.3.0` and `cy2@4.0.5`). Probably Cypress guys added some breaking changes in how they deal with the file system, I'm not sure.

**Comment by agoldis** [comment]
You guys should tell them to stop tweaking the package and focus on the product instead. 

As a side note - cy2 is not patching cypress package anymore, it's using its public APIs so there'd no problem with running multiple instances on the same system (cy2-related).
