### ISSUE TITLE
Unable to use CY2 with a https baseUrl

### ISSUE THREAD

**Issue by richardmward** [sorry-cypress/cy2#50]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/cy2/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/cy2/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Environment information

<details>

```
  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 8.24 GB / 31.89 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.17.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 108.0.5359.125
    Edge: Spartan (44.19041.1266.0)

```

</details>

### Describe the bug

Using cy2 4.0.1 and Cypress 12.3.0 I am unable to use the new `run` command with an `https` `baseUrl` in my config (see logs below). This was working a few days ago as I was just having trouble then with the command not returning the promise (https://github.com/sorry-cypress/cy2/issues/38#issuecomment-1371027760). 

### Expected behavior

To be able to use an `https` `baseUrl`. 

### Log and debug output

<details>

```
  cypress:server:ensure-url checking that baseUrl is available {
  baseUrl: 'https://www.example.com',
  delaysRemaining: [ 3000, 3000, 4000 ],
  retryIntervals: [ 3000, 3000, 4000 ]
} +0ms
  cypress:network:agent addRequest called { isHttps: true, href: 'https://www.example.com/' } +0ms
  cypress:network:agent got family { family: undefined, href: 'https://www.example.com/' } +4ms
  cypress:network:agent Creating proxied socket for https://www.example.com/ through https://undefined +8ms
  cypress:network:connect retries exhausted, bubbling up error { iteration: 0, err: Error: getaddrinfo ENOTFOUND undefined     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) { errno: -3008, code: 'ENOTFOUND', syscall: 'getaddrinfo', hostname: 'undefined' } } +0ms
Cypress could not verify that this server is running:

  > https://www.example.com

We are verifying this server because it has been configured as your baseUrl.
```

</details>

### Additional information and screenshots

Self hosted Sorry Cypress instance

**Comment by pkell** [comment]
Having the same issue.
Interestingly it only happens when calling cy2.run
I can successfully run using the CLI

**Comment by agoldis** [comment]
@richardmward @pkell would appreciate if you share:
- the exact commands or code you're using to invoke `cy2`
- the full log starting from the execution till the error - it has some init output that's important for troubelshooting

**Comment by pkell** [comment]
@agoldis Is there a specific debug i should set for cypress to cut it down to what you need?
I did just notice this when running programmatically

 cypress:network:agent Creating proxied socket for https://mytesturl/ through https://undefined +2ms

The undefined is instead   cypress:network:agent Creating proxied socket for https://mytesturl/ through http://127.0.0.1:62761 +4ms
when running through CLI

**Comment by agoldis** [comment]
Please try cy2@4.0.2

**Comment by agoldis** [comment]
Reopening until received the confirmation

**Comment by richardmward** [comment]
That works, thanks (and thanks for changing to `Partial<CypressCommandLine.CypressRunOptions>` - I was going to raise that!)

The promise still doesn't resolve, so it ends up never returning from `await run(...)`. The logs after the test run are as follows, and then it just sits there:

```
  cypress:server:cypress about to exit with code 5 +2m
  cypress:server:browsers browsers.kill called with no active instance +9s
  cypress:proxy:http:util:prerequests metrics: { browserPreRequestsReceived: 140, proxyRequestsReceived: 10, immediatelyMatchedRequests: 10, unmatchedRequests: 0, unmatchedPreRequests: 106 } +0ms

───────────────────────────────────────────────────────────────────────────────────────────────────────

  Recorded Run: https://my-director-service.com/run/2a1898e59103f870b53e178d5a46eece

  cypress:cli child event fired { event: 'exit', code: 5, signal: null } +2m
  cypress:cli child event fired { event: 'close', code: 5, signal: null } +1ms
  ```

**Comment by agoldis** [comment]
@richardmward [this](https://github.com/sorry-cypress/cy2/pull/53/files#diff-78bb005ca752086400a648d8aa3e60ce6f666e213da508caabd464d3bfeaf6a2R49) should resolve the issue with a hung promise. Please try out cy2@4.0.3

**Comment by richardmward** [comment]
Spot on. Thank you!

**Comment by pkell** [comment]
@agoldis Works perfectly now. Thanks again!

**Comment by agoldis** [comment]
🎉
