### ISSUE TITLE
Suggestion: Allow ability to add custom headers into cy2 proxy

### ISSUE THREAD

**Issue by richardmward** [sorry-cypress/cy2#52]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/cy2/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/cy2/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Environment information

<details>

```
N/A
```

</details>

### Describe the bug

I run a proxy before starting a test run in order to add in an authentication header as part of the request to my sorry cypress director service (which is configured to run behind an OAuth proxy). As cy2 uses a proxy as part of it's solution to reroute requests to an alternative director service, it'd be handy if I could configure custom headers on that proxy service instead of having to run my own additional one.

### Expected behavior

N/A

### Command and Setup

N/A

### Full log and debug output

<details>

```
N/A
```

</details>

**Comment by agoldis** [comment]
Good idea...In case there's an existing proxy upstream proxy, we need to use the right headers for the right destinations.

**Comment by qraleq** [comment]
This is a great proposal! 
@richardmward Can you please explain how you handle the auth header injection?
Thank you!
