### ISSUE TITLE
v4.0.5 does not support a local (non-https) proxy

### ISSUE THREAD

**Issue by richardmward** [sorry-cypress/cy2#58]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/cy2/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/cy2/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Environment information

<details>

```
  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 5.84 GB / 31.89 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.17.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 108.0.5359.125
    Edge: Spartan (44.19041.1266.0)
```

</details>

### Describe the bug

Since v4.0.5, cy2 does not work with a local proxy (used to add auth headers) getting `RequestError: Error: ESOCKETTIMEDOUT`. It may be that it is because it is not a proper proxy (just a simple http server that receives requests and makes equivalent requests with axios) - but it was working before and now isn't, so wanted to raise to see if it is expected to work or not?

### Expected behavior

Essentially the setup is like running a local director service over http - which I would expect to work?

### Command and Setup

```
const localHttpServerUrl = await startLocalServer();
run(localHttpServerUrl, { ... });
```

### Full log and debug output

<details>

```
We encountered an unexpected error talking to our servers.

We will retry 3 more times in 30 seconds...

The server's response was:

RequestError: Error: ESOCKETTIMEDOUT
```

</details>

**Comment by agoldis** [comment]
As a side note, here's an e2e test we run to test an upstream proxy https://github.com/sorry-cypress/cy2/actions/runs/3890660082/jobs/6639997079#step:9:1

You'd probably set HTTP_PROXY env variable before invoking `run`
