### ISSUE TITLE
I think cy2(using v4.0.5) not follow the cypress.config.ts (using cypress 12.3.0)

### ISSUE THREAD

**Issue by shye0000** [sorry-cypress/cy2#60]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/cy2/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/cy2/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I acknowledge that I will attach a **full debug log**, otherwise the issue will be closed with no response.

### Environment information

<details>

```
# Put output below this line
 System:
    OS: Linux 5.15 Linux Mint 20.2 (Uma)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz
    Memory: 4.80 GB / 30.57 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 107.0
  npmPackages:
    eslint-config-prettier: ^8.3.0 => 8.5.0 
    eslint-plugin-prettier: ^4.0.0 => 4.2.1 
    husky: ^4.3.0 => 4.3.8 
    lint-staged: ^11.2.3 => 11.2.6 
    prettier: ^2.4.1 => 2.7.1 
    typescript: ~4.8.4 => 4.8.4 
  npmGlobalPackages:
    @expo/ngrok: 4.1.0
    @vue/cli: 5.0.6
    corepack: 0.10.0
    expo-cli: 5.0.3
    gtop: 1.1.3
    jscodeshift: 0.14.0
    npm: 8.19.2
    svgo: 2.8.0
    vtop: 0.6.1

```

</details>

### Describe the bug

Having this error with cy2 (it tries to find tests in the default folder "cypress/intergration")
![image](https://user-images.githubusercontent.com/6414361/212465846-b8071f89-1409-4dc7-bb09-55f661029dbe.png)

But in the cypress.config.ts, I have this cutomized:
![image](https://user-images.githubusercontent.com/6414361/212465923-78eb0453-2d6d-4156-8a64-c76c2502a8a2.png)

So it seems to me that cy2 does not follow correctly the cypress configuration file.

### Expected behavior

find tests in my customized directory and follow the other cypress configurations too.

### Command and Setup

`CYPRESS_PROJECT_ID=foo cy2 run --headless --record --parallel --key bar --ci-build-id $CI_PIPELINE_ID`

### Full log and debug output

<details>

```
// Put your logs below this line
++ npm run test:e2e
> root@1.0.0 test:e2e
> npm run test:e2e --workspace=@neo1/web
> @neo1/web@1.0.0 test:e2e
> npm run test:e2e:dist
> @neo1/web@1.0.0 test:e2e:dist
> { if [ -z "$VERSION" ]; then export VERSION=$(node -p "require('./package.json').version"); fi } && sed 's@<head>@<head><script>window.Neo={debugMode:true}</script>@' build/*/index.html > build/index.html && node scripts/assetsAndProxyServer/index.js server build & CYPRESS_PROJECT_ID=foo cy2 run --headless --record --parallel --key bar --ci-build-id $CI_PIPELINE_ID
server listening on port 3000 : http://localhost:3000
 [cy2]  Using cloud orchestration service: http://sorry-cypress.itprod.internal.neo1.com:1234
It looks like this is your first time using Cypress: 9.7.0
[STARTED] Task without title.
[SUCCESS] Task without title.
Opening Cypress...
[342:0114/092928.962252:ERROR:node_bindings.cc(276)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
[496:0114/092930.384[54](https://gitlab.kdsneo.kds.com/neo1/neo-one-ui/-/jobs/435458#L54)9:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[496:0114/092930.387471:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
Can't run because no spec files were found.
We searched for specs inside of this folder:
  > /builds/neo1/neo-one-ui/apps/web/cypress/integration

```

</details>

**Comment by agoldis** [comment]
You're using cypress `9.7.0`  and trying to use the [new configuration](https://docs.cypress.io/guides/references/configuration) syntax instead of [legacy syntax](https://docs.cypress.io/guides/references/legacy-configuration#docusaurus_skipToContent_fallback)

**Comment by shye0000** [comment]
? Im confused... I am using the new syntax I think, no? `specPattern` in `e2e` is the new syntax no?

**Comment by agoldis** [comment]
It is supported in 10+

**Comment by shye0000** [comment]
arf, I see, my bad, the cypress installed in the stupid CI is 9.7.0, sorry for the noises
