### ISSUE TITLE
Can't connect to CYPRESS_API_URL (config didn't changed)

### ISSUE THREAD

**Issue by samixchoumi** [sorry-cypress/cy2#66]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/cy2/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/cy2/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I acknowledge that I will attach a **full debug log**, otherwise the issue will be closed with no response.

### Environment information

<details>

</details>

### Describe the bug

It worked this morning (and all previous week) and for no reason (no update was done), i got this error and then parallelization fail.

Error message : 
```
 WARNING  Error connecting to http://[MASKED]:1234/: connect ECONNREFUSED 10.3.8.6:1234 
We encountered an unexpected error talking to our servers.
We will retry 3 more times in 30 seconds...
The server's response was:
RequestError: Error: ESOCKETTIMEDOUT
```

### Expected behavior

Parallelization work fine as usual.

### Command and Setup

I launch this command into my GitLab CI : `npx cy2 run --record --key XXX --parallel --ci-build-id $CI_PIPELINE_ID --env allure=true,configFile=dev --browser chrome --headless` 

### Full log and debug output

<details>

```
// Put your logs below this line


```

</details>

**Comment by agoldis** [comment]
Missing required details
