### ISSUE TITLE
Should have an option to skip coverage for other origins while testing

### ISSUE THREAD

**Issue by TeufikUmihanic** [sorry-cypress/cy2#67]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/cy2/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/cy2/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I acknowledge that I will attach a **full debug log**, otherwise the issue will be closed with no response.

### Environment information

<details>

```
# Put output below this line
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
    Memory: 3.51 GB / 15.73 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (110.0.1587.41)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @cypress/angular:  0.0.0-development
    @cypress/code-coverage: ^3.10.0 => 3.10.0
    @cypress/mount-utils:  0.0.0-development
    @cypress/react:  0.0.0-development
    @cypress/react18:  0.0.0-development
    @cypress/svelte:  0.0.0-development
    @cypress/vue:  0.0.0-development
    @cypress/vue2:  0.0.0-development
    @nuintun/qrcode: ^3.3.0 => 3.3.0
    @typescript-eslint/eslint-plugin: ^5.40.1 => 5.48.1
    @typescript-eslint/parser: ^5.40.1 => 5.48.1
    archiver: ^5.3.1 => 5.3.1
    chalk: ^4.1.2 => 4.1.2 (2.4.2)
    cy2: ^3.4.3 => 3.4.3
    cypress: ^12.5.1 => 12.5.1
    cypress-cucumber-preprocessor: ^4.3.1 => 4.3.1
    cypress-file-upload: ^5.0.8 => 5.0.8
    cypress-parallel: ^0.10.0 => 0.10.0
    cypress-recurse: ^1.27.0 => 1.27.0
    dotenv: ^16.0.3 => 16.0.3
    eslint: ^8.22.0 => 8.22.0
    eslint-config-prettier: ^8.5.0 => 8.6.0
    eslint-plugin-prettier: ^4.2.1 => 4.2.1
    eslint-plugin-simple-import-sort: ^9.0.0 => 9.0.0
    form-data: ^4.0.0 => 4.0.0 (2.3.3)
    helper: file:helper => 1.0.0
    expo-cli: 6.2.1
    node-gyp: 9.0.0
    pnpm: 7.26.3
    selenium-side-runner: 3.17.0
    truffle: 5.5.15
    yarn: 1.22.19

```

</details>

### Describe the bug

Code coverage works OK in tests that are not causing opening of another origin in same or new tab. But tests that have any link or action that leads us from our application we test will cause this issue.

### Expected behavior

Test should pass even when we are opening new origin.

### Command and Setup

cypress run
cypress open

### Full log and debug output

<details>

```
// Put your logs below this line
Permission denied to access property "coverage" on cross-origin object

> 70 |       const applicationSourceCoverage = win.__coverage__

```

</details>

**Comment by agoldis** [comment]
Is it related to `cy2`?

**Comment by TeufikUmihanic** [comment]
```
Permission denied to access property "coverage" on cross-origin object

> 70 |       const applicationSourceCoverage = win.__coverage__
```

because of cy2 error my tests are failing, but only the ones that have visiting another origin from my application.
Can this error be skipped for this cases?

**Comment by agoldis** [comment]
@TeufikUmihanic why do you think it is because of cy2?

**Comment by TeufikUmihanic** [comment]
Hmmm when I check it better you are right, this has to do something with code coverage lib we use. Sorry and thanks for your response
