### ISSUE TITLE
Your Record Key XXX...XXX is not valid with this projectId

### ISSUE THREAD

**Issue by TeufikUmihanic** [sorry-cypress/cy2#68]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/cy2/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/cy2/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I acknowledge that I will attach a **full debug log**, otherwise the issue will be closed with no response.

### Environment information

<details>

```
# Put output below this line
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
    Memory: 1.99 GB / 15.73 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (110.0.1587.41)
    Internet Explorer: 11.0.22621.1
npmPackages:
    cy2: ^4.0.5 => 4.0.5
    cypress: ^12.2.0 => 12.2.0

```

</details>

### Describe the bug

On my pipeline I'm using `cypress/browsers:node16.18.0-chrome107-ff106-edge` and there I'm having error:
`Your Record Key XXX...XXX is not valid with this projectId: APARI`

Locally when I run `npx cy2 run --record --browser chrome --key XXX --parallel --ci-build-id test && set DEBUG=cy2` with provided cy and cy2 version I'm getting error:

```
C:\Users\usr\Documents\apari\e2e-testing\node_modules\requires-port\index.js:13
  protocol = protocol.split(':')[0];
                      ^
TypeError: Cannot read properties of null (reading 'split')
```

### Expected behavior

-

### Command and Setup

npx cy2 run --record --browser chrome --key XXX --parallel --ci-build-id $BITBUCKET_BUILD_NUMBER

### Full log and debug output

<details>

```
// Put your logs below this line
Your Record Key XXX...XXX is not valid with this projectId: _____
It may have been recently revoked by you or another user.
Please log into Cypress Cloud to see the valid Record Keys.

```

</details>

**Comment by agoldis** [comment]
Hey @TeufikUmihanic please follow the template instructions
