### ISSUE TITLE
Upload videos for flake tests

### ISSUE THREAD

**Issue by josefsmrz** [sorry-cypress/cy2#73]
### Description

When tests that have failed actually pass after a retry and videoUploadOnPasses: false flag is used, videos are currently not uploaded. It would be very nice to upload them also, because I could then investigate what was the cause of the flake and get rid of it.[](url)

### Example usage

When I use `videoUploadOnPasses: false` and `retries` that is not zero, the video should be uploaded to the dashboad.

**Comment by agoldis** [comment]
That should go to cypress repo

**Comment by josefsmrz** [comment]
Okay, I wasn't sure, thank you.
