### ISSUE TITLE
Cant run sorry cypress with cypress ntlm after V12 upgrade

### ISSUE THREAD

**Issue by Benhackmon** [sorry-cypress/cy2#77]
### Before opening, please confirm:

- [x] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/cy2/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/cy2/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I acknowledge that I will attach a **full debug log**, otherwise the issue will be closed with no response.

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

After upgrade cypress to v12.2.0 and cy2 to V4
I tried to run sorry cypress with cypress-ntlm,
Script in CMD:
      Call npx cy2
      npx cypress-ntlm run --record --key....

In version 10.6.0 with cy2 it worked but when cypress changed their configuration it's not working anymore.
I tried to run The ntlm-proxy manually but failed.
I also tried to run the same command but now when i call cy2 it runs the tests

### Expected behavior

Having a script that can run sorry cypress but with ntlm
Or the last script will work

### Command and Setup

Cmd file sorry-cypress.cmd:
call cy2
npx cypress-ntlm run --record.....

And then i ran the script

### Full log and debug output

<details>

```
// Put your logs below this line


```

</details>

**Comment by agoldis** [comment]
Hey @Benhackmon, 
You'd at least post some troubleshooting information.
